kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: export-sharedv4-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"
   sharedv4: "true"
   allow_all_ips: "true"
